{
 "title": "Real-Time Monitoring",
 "description": "Monitor real-time changes in weather and AQI, comparing them with local satisfaction and AI driven predictions.",
 "time": { "from": "now-16h", "to": "now" },
 "refresh": "1h",
 "panels": [
  { "title": "Mean Regional AQI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Islamabad - AQI",
   "type": "timeseries",
   "description": "The AQI in Islamabad, Pakistan. \nSource: https://api.waqi.info/",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"islamabadAQI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AQI\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Lahore - AQI",
   "type": "timeseries",
   "description": "The AQI in Lahore, Pakistan. \nSource: https://api.waqi.info/",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"lahoreAQI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AQI\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Karachi - AQI",
   "type": "timeseries",
   "description": "The Air Quality Index in Karachi, Pakistan. \nSource: https://api.waqi.info/\n",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"karachiAQI\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AQI\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Mean Regional Temperatures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Islamabad - Temperature",
   "type": "timeseries",
   "description": "The mean temperature in Islamabad, Pakistan. \nSource: http://openweathermap.org",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"islamabadWeather\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Lahore - Temperature",
   "type": "timeseries",
   "description": "The mean temperature in Lahore, Pakistan. \nSource: http://openweathermap.org",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"lahoreWeather\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Karachi Temperature",
   "type": "timeseries",
   "description": "The mean temperature in Karachi, Pakistan. \nSource: http://openweathermap.org",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"karachiWeather\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Predicted Local Satisfaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Islamabad - Predicted Satisfaction",
   "type": "timeseries",
   "description": "Predicted satisfaction for temperature and air quality in Islamabad, based on live data.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"islamabadPredictions\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"raw\")"
    },
    {
     "query": "from(bucket: \"islamabadPredictions\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AQI\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"raw\")"
    }
   ]
  },
  {
   "title": "Lahore - Predicted Satisfaction",
   "type": "timeseries",
   "description": "Predicted satisfaction for temperature and air quality in Lahore, based on live data.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"lahorePredictions\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"raw\")"
    },
    {
     "query": "from(bucket: \"lahorePredictions\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AQI\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"raw\")"
    }
   ]
  },
  {
   "title": "Karachi - Predicted Satisfaction",
   "type": "timeseries",
   "description": "Predicted satisfaction for temperature and air quality in Karachi, based on live data.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"karachiPredictions\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Temperature\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"raw\")"
    },
    {
     "query": "from(bucket: \"karachiPredictions\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"AQI\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"_value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"raw\")"
    }
   ]
  },
  { "title": "What Locals Say", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Islamabad- Average Local Satisfaction",
   "type": "timeseries",
   "description": "The average of all local views of weather of air quality in Islamabad, Pakistan.\n\nThis data is entirely subjective and was obtained by asking users the question, \"What does the air quality feel like in your area? A higher score indicates better air quality\"\nand,\n\"What does the weather feel like in your area? A higher score indicates better weather conditions\"",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "targets": [
    {},
    {
     "query": "period = 30m     // how wide each window is (more width = smoother)\r\nevery  = 1m     // how often we emit a window (smaller = denser / smoother)\r\n\r\nfrom(bucket: \"islamabadFeelsLike\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n       (r._measurement == \"AirQuality\" and r._field == \"_value\") or\r\n       (r._measurement == \"Weather\"    and r._field == \"_value\")\r\n     )\r\n  |> group(columns: [\"_measurement\"])        // compute separately per measurement\r\n  |> window(every: every, period: period, createEmpty: false) \r\n  |> mean()                                 // mean over each sliding window\r\n  |> map(fn: (r) => ({ r with _time: r._stop })) // put the point at window end (or use _start)\r\n  |> group(columns: [\"_measurement\"])        // re-group for plotting if needed\r\n  |> yield(name: \"sliding_time_window_mean\")\r\n"
    }
   ]
  },
  {
   "title": "Lahore - Average Local Satisfaction",
   "type": "timeseries",
   "description": "The average of all local views of weather of air quality in Lahore, Pakistan.\n\nThis data is entirely subjective and was obtained by asking users the question, \"What does the air quality feel like in your area? A higher score indicates better air quality\"\nand,\n\"What does the weather feel like in your area? A higher score indicates better weather conditions\"",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "targets": [
    {},
    {
     "query": "period = 30m     // how wide each window is (more width = smoother)\r\nevery  = 1m     // how often we emit a window (smaller = denser / smoother)\r\n\r\nfrom(bucket: \"lahoreFeelsLike\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n       (r._measurement == \"AirQuality\" and r._field == \"_value\") or\r\n       (r._measurement == \"Weather\"    and r._field == \"_value\")\r\n     )\r\n  |> group(columns: [\"_measurement\"])        // compute separately per measurement\r\n  |> window(every: every, period: period, createEmpty: false) \r\n  |> mean()                                 // mean over each sliding window\r\n  |> map(fn: (r) => ({ r with _time: r._stop })) // put the point at window end (or use _start)\r\n  |> group(columns: [\"_measurement\"])        // re-group for plotting if needed\r\n  |> yield(name: \"sliding_time_window_mean\")\r\n"
    }
   ]
  },
  {
   "title": "Karachi - Average Local Satisfaction",
   "type": "timeseries",
   "description": "The average of all local views of weather of air quality in Karachi, Pakistan.\n\nThis data is entirely subjective and was obtained by asking users the question, \"What does the air quality feel like in your area? A higher score indicates better air quality\"\nand,\n\"What does the weather feel like in your area? A higher score indicates better weather conditions\"",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "targets": [
    {
     "query": "period = 30m     // how wide each window is (more width = smoother)\r\nevery  = 1m     // how often we emit a window (smaller = denser / smoother)\r\n\r\nfrom(bucket: \"karachiFeelsLike\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n       (r._measurement == \"AirQuality\" and r._field == \"_value\") or\r\n       (r._measurement == \"Weather\"    and r._field == \"_value\")\r\n     )\r\n  |> group(columns: [\"_measurement\"])        // compute separately per measurement\r\n  |> window(every: every, period: period, createEmpty: false) \r\n  |> mean()                                 // mean over each sliding window\r\n  |> map(fn: (r) => ({ r with _time: r._stop })) // put the point at window end (or use _start)\r\n  |> group(columns: [\"_measurement\"])        // re-group for plotting if needed\r\n  |> yield(name: \"sliding_time_window_mean\")\r\n"
    }
   ]
  },
  {
   "title": "Islamabad - Local Satisfaction",
   "type": "timeseries",
   "description": "A view of how satisfied locals are of the local conditions in Islamabad, Pakistan.\n\nThis data is entirely subjective and was obtained by asking users the question, \"What does the air quality feel like in your area? A higher score indicates better air quality\"\nand,\n\"What does the weather feel like in your area? A higher score indicates better weather conditions\"\n",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "targets": [
    {
     "query": "from(bucket: \"islamabadFeelsLike\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n       (r._measurement == \"AirQuality\" and (r._field == \"_value\")) or\r\n       (r._measurement == \"Weather\" and (r._field == \"_value\"))\r\n     )\r\n"
    }
   ]
  },
  {
   "title": "Lahore - Local Satisfaction",
   "type": "timeseries",
   "description": "A view of how satisfied locals are of the local conditions in Lahore, Pakistan.\n\nThis data is entirely subjective and was obtained by asking users the question, \"What does the air quality feel like in your area? A higher score indicates better air quality\"\nand,\n\"What does the weather feel like in your area? A higher score indicates better weather conditions\"",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "targets": [
    {
     "query": "from(bucket: \"lahoreFeelsLike\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n       (r._measurement == \"AirQuality\" and (r._field == \"_value\")) or\r\n       (r._measurement == \"Weather\" and (r._field == \"_value\"))\r\n     )\r\n"
    }
   ]
  },
  {
   "title": "Karachi - Local Satisfaction",
   "type": "timeseries",
   "description": "A view of how satisfied locals are of the local conditions in Karachi, Pakistan.\n\nThis data is entirely subjective and was obtained by asking users the question, \"What does the air quality feel like in your area? A higher score indicates better air quality\"\nand,\n\"What does the weather feel like in your area? A higher score indicates better weather conditions\"",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "targets": [
    {
     "query": "from(bucket: \"karachiFeelsLike\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n       (r._measurement == \"AirQuality\" and (r._field == \"_value\")) or\r\n       (r._measurement == \"Weather\" and (r._field == \"_value\"))\r\n     )\r\n"
    }
   ]
  }
 ]
}